export enum USER_ROLE {
    STUDENT = "STUDENT",
    PARENT = "PARENT",
    COUNSELOR = "COUNSELOR",
    ALUMNI = "ALUMNI",
    ADMIN = "ADMIN",
    SUPERADMIN = "SUPERADMIN",
    SERVICE_PROVIDER = "SERVICE_PROVIDER",
  }